apiVersion: v1
kind: Service
metadata:
  name: consensus-layer-svc
spec:
  type: ClusterIP
  selector:
    app: consensus-layer
  ports:
    - name: rpc
      port: 5052
      protocol: TCP
      targetPort: rpc
    - name: http
      port: 5053
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 5054
      protocol: TCP
      targetPort: metrics
    - name: peering-tcp
      port: 9000
      protocol: TCP
      targetPort: peering-tcp
    - name: peering-udp
      port: 9000
      protocol: UDP
      targetPort: peering-udp
    - name: peering
      port: 9001
      protocol: UDP
      targetPort: peering
