apiVersion: v1
kind: Service
metadata:
  name: consensus-layer-svc
spec:
  type: ClusterIP
  selector:
    app: consensus-layer
  ports:
    - name: consensus-rpc
      port: 5052
      protocol: TCP
      targetPort: rpc
    - name: consensus-http
      port: 5053
      protocol: TCP
      targetPort: http
    - name: consensus-metrics
      port: 5054
      protocol: TCP
      targetPort: metrics
    - name: consensus-peeringTcp
      port: 9000
      protocol: TCP
      targetPort: peeringTcp
    - name: consensus-peeringUdp
      port: 9000
      protocol: UDP
      targetPort: peeringUdp
    - name: consensus-peering
      port: 9001
      protocol: UDP
      targetPort: peering
