apiVersion: apps/v1
kind: Deployment
metadata:
  name: consensus-layer
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: consensus-layer
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5054"
      labels:
        app: consensus-layer
    spec:
      initContainers:
      - name: jwttoken
        image: alpine/openssl:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "/mnt/scripts/generate-token.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /mnt/scripts
        - name: jwt-token-volume
          mountPath: /mnt/jwt
      containers:
      - name: lighthouse
        image: sigp/lighthouse:v5.1.3-modern
        imagePullPolicy: IfNotPresent
        ports:
        - name: rpc
          containerPort: 5052
          protocol: TCP
        - name: http
          containerPort: 5053
          protocol: TCP
        - name: metrics
          containerPort: 5054
          protocol: TCP
        - name: peering-tcp
          containerPort: 9000
          protocol: TCP
        - name: peering-udp
          containerPort: 9000
          protocol: UDP
        - name: peering
          containerPort: 9001
          protocol: UDP
        command:
        - lighthouse bn
        - --network mainnet
        - --http --http-address 0.0.0.0
        - --execution-endpoint http://reth:8551
        - --metrics --metrics-address 0.0.0.0
        - --execution-jwt /mnt/jwttoken/jwt.hex
        - --checkpoint-sync-url https://mainnet.checkpoint.sigp.io
        #env:
        #- name: PODINFO_UI_COLOR
          #value: "#34577c"
        #livenessProbe:
          #exec:
            #command:
            #- podcli
            #- check
            #- http
            #- localhost:9898/healthz
          #initialDelaySeconds: 5
          #timeoutSeconds: 5
        #readinessProbe:
          #exec:
            #command:
            #- podcli
            #- check
            #- http
            #- localhost:9898/readyz
          #initialDelaySeconds: 5
          #timeoutSeconds: 5
        resources:
          limits:
            cpu: 3000m
            memory: 10240Mi
          requests:
            cpu: 2000m
            memory: 8192Mi
        volumeMounts:
          - name: jwt-token-volume
            mountPath: /mnt/jwttoken
      volumes:
        - name: script-volume
          configMap:
            name: jwt-script-configmap
        - name: jwt-token-volume
          emptyDir: {}

