apiVersion: v1
kind: Service
metadata:
  name: execution-layer-svc
spec:
  type: ClusterIP
  selector:
    app: execution-layer
  ports:
    - name: execution-rpc
      port: 8545
      protocol: TCP
      targetPort: rpc
    - name: execution-engine
      port: 8551
      protocol: TCP
      targetPort: engine
    - name: execution-metrics
      port: 5055
      protocol: TCP
      targetPort: metrics
    - name: execution-peering
      port: 30303
      protocol: TCP
      targetPort: peering
