apiVersion: v1
kind: Service
metadata:
  name: execution-layer
spec:
  type: ClusterIP
  selector:
    app: execution-layer
  ports:
    - name: rpc
      port: 8545
      protocol: TCP
      targetPort: rpc
    - name: engine
      port: 8551
      protocol: TCP
      targetPort: engine
    - name: metrics
      port: 5055
      protocol: TCP
      targetPort: metrics
    - name: peering
      port: 30303
      protocol: TCP
      targetPort: peering
