apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-layer
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5055"
        prometheus.io/path: "/"
      labels:
        app: execution-layer
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: reth
          image: ghcr.io/paradigmxyz/reth
          imagePullPolicy: IfNotPresent
          ports:
            - name: rpc
              containerPort: 8545
              protocol: TCP
            - name: engine
              containerPort: 8551
              protocol: TCP
            - name: metrics
              containerPort: 5055
              protocol: TCP
            - name: peering
              containerPort: 30303
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              reth node --chain mainnet --metrics 0.0.0.0:5055 --log.file.directory /logs --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.jwtsecret /mnt/token/jwt --http --http.addr 0.0.0.0 --http.port 8545 --http.api "eth,net,web3"
          resources:
            limits:
              cpu: 2000m
              memory: 6144Mi
            requests:
              cpu: 1000m
              memory: 4096Mi
          volumeMounts:
            - name: jwt-secret-volume
              readOnly: true
              mountPath: /mnt/token
            - name: logs
              mountPath: /logs
            - name: local
              mountPath: /.local
      volumes:
        - name: jwt-secret-volume
          secret:
            secretName: jwt-secret
            defaultMode: 0770
        - name: logs
          emptyDir: {}
        - name: local
          emptyDir: {}
