---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ethereum-node-automation
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: ethereum-node-automation
  targetNamespace: ethereum-node-automation
  timeout: 3m0s
  wait: true
